/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as MyLibraryRouteImport } from './routes/my-library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameSlugRouteImport } from './routes/game.$slug'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLibraryRoute = MyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSlugRoute = GameSlugRouteImport.update({
  id: '/game/$slug',
  path: '/game/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/genres': typeof GenresRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/my-library': typeof MyLibraryRoute
  '/upcoming': typeof UpcomingRoute
  '/game/$slug': typeof GameSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/genres': typeof GenresRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/my-library': typeof MyLibraryRoute
  '/upcoming': typeof UpcomingRoute
  '/game/$slug': typeof GameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/genres': typeof GenresRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/my-library': typeof MyLibraryRoute
  '/upcoming': typeof UpcomingRoute
  '/game/$slug': typeof GameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/genres'
    | '/library'
    | '/login'
    | '/my-library'
    | '/upcoming'
    | '/game/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/genres'
    | '/library'
    | '/login'
    | '/my-library'
    | '/upcoming'
    | '/game/$slug'
  id:
    | '__root__'
    | '/'
    | '/complete-profile'
    | '/genres'
    | '/library'
    | '/login'
    | '/my-library'
    | '/upcoming'
    | '/game/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  GenresRoute: typeof GenresRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MyLibraryRoute: typeof MyLibraryRoute
  UpcomingRoute: typeof UpcomingRoute
  GameSlugRoute: typeof GameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-library': {
      id: '/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof MyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$slug': {
      id: '/game/$slug'
      path: '/game/$slug'
      fullPath: '/game/$slug'
      preLoaderRoute: typeof GameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  GenresRoute: GenresRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MyLibraryRoute: MyLibraryRoute,
  UpcomingRoute: UpcomingRoute,
  GameSlugRoute: GameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
